spring:
  application:
    name: my-wine-cellar
  data:
    mongodb:
      uri: mongodb+srv://edsonfri:tAqod0IBwAs4ju4P@winecellar.z0ypncj.mongodb.net/?retryWrites=true&w=majority&appName=winecellar
      username:
      password:
      database: wine_cellar

server:
  servlet:
    con text-path: /myWineCellar/v1
  port: ${PORT:8080}